### PR TITLE
shabbos ends opinions

### PR DESCRIPTION
**Pull request by yparitcher**
add the ability to select minutes after a differnt zman than the one set for sunset/twilight/nightfall

### CODE REVIEW

**Comment by pnemonic78** [comment]
I saw your intention, so I just took the bits we really need.

**Comment by yparitcher** [comment]
Thank you, however i was trying to allow for different opinions between nightfall and shabbos ends, as many in the chabad community use 6 degrees for nightfall and are machmir to 8.5 degrees for shabbos ends

**Comment by pnemonic78** [comment]
Ok, will add as extra option...

**Comment by yparitcher** [comment]
fixed in 10b77a1a30ad815d61f9ac707aeb54266635f8b4 thanks

**Pull request closed without merging**
